// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "mesh.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace mesh {

namespace {

const ::google::protobuf::Descriptor* Mesh_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Mesh_reflection_ = NULL;
const ::google::protobuf::Descriptor* Mesh_Layer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Mesh_Layer_reflection_ = NULL;
const ::google::protobuf::Descriptor* Quaternion_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Quaternion_reflection_ = NULL;
const ::google::protobuf::Descriptor* Vector_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Vector_reflection_ = NULL;
const ::google::protobuf::Descriptor* Transform_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Transform_reflection_ = NULL;
const ::google::protobuf::Descriptor* Animation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Animation_reflection_ = NULL;
const ::google::protobuf::Descriptor* Animation_Keyframe_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Animation_Keyframe_reflection_ = NULL;
const ::google::protobuf::Descriptor* Skeleton_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Skeleton_reflection_ = NULL;
const ::google::protobuf::Descriptor* Skeleton_Relationship_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Skeleton_Relationship_reflection_ = NULL;
const ::google::protobuf::Descriptor* Skeleton_Bone_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Skeleton_Bone_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_mesh_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  Mesh_descriptor_ = file->message_type(0);
  Mesh::default_instance_ = new Mesh();
  static const int Mesh_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, layers_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, indices_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, primitive_type_),
  };
  Mesh_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Mesh_descriptor_,
      Mesh::default_instance_,
      Mesh_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Mesh));
  Mesh_Layer_descriptor_ = Mesh_descriptor_->nested_type(0);
  Mesh_Layer::default_instance_ = new Mesh_Layer();
  static const int Mesh_Layer_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh_Layer, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh_Layer, columns_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh_Layer, rows_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh_Layer, data_),
  };
  Mesh_Layer_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Mesh_Layer_descriptor_,
      Mesh_Layer::default_instance_,
      Mesh_Layer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh_Layer, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh_Layer, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Mesh_Layer));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Mesh_Layer_descriptor_, Mesh_Layer::default_instance_);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Mesh_descriptor_, Mesh::default_instance_);
  Quaternion_descriptor_ = file->message_type(1);
  Quaternion::default_instance_ = new Quaternion();
  static const int Quaternion_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quaternion, r_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quaternion, i_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quaternion, j_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quaternion, k_),
  };
  Quaternion_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Quaternion_descriptor_,
      Quaternion::default_instance_,
      Quaternion_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quaternion, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quaternion, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Quaternion));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Quaternion_descriptor_, Quaternion::default_instance_);
  Vector_descriptor_ = file->message_type(2);
  Vector::default_instance_ = new Vector();
  static const int Vector_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector, z_),
  };
  Vector_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Vector_descriptor_,
      Vector::default_instance_,
      Vector_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Vector, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Vector));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Vector_descriptor_, Vector::default_instance_);
  Transform_descriptor_ = file->message_type(3);
  Transform::default_instance_ = new Transform();
  static const int Transform_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, translation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, rotation_),
  };
  Transform_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Transform_descriptor_,
      Transform::default_instance_,
      Transform_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Transform, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Transform));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Transform_descriptor_, Transform::default_instance_);
  Animation_descriptor_ = file->message_type(4);
  Animation::default_instance_ = new Animation();
  static const int Animation_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation, duration_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation, keyframes_),
  };
  Animation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Animation_descriptor_,
      Animation::default_instance_,
      Animation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Animation));
  Animation_Keyframe_descriptor_ = Animation_descriptor_->nested_type(0);
  Animation_Keyframe::default_instance_ = new Animation_Keyframe();
  static const int Animation_Keyframe_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation_Keyframe, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation_Keyframe, bone_transforms_),
  };
  Animation_Keyframe_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Animation_Keyframe_descriptor_,
      Animation_Keyframe::default_instance_,
      Animation_Keyframe_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation_Keyframe, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Animation_Keyframe, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Animation_Keyframe));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Animation_Keyframe_descriptor_, Animation_Keyframe::default_instance_);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Animation_descriptor_, Animation::default_instance_);
  Skeleton_descriptor_ = file->message_type(5);
  Skeleton::default_instance_ = new Skeleton();
  static const int Skeleton_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton, bones_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton, hierarchy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton, animations_),
  };
  Skeleton_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Skeleton_descriptor_,
      Skeleton::default_instance_,
      Skeleton_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Skeleton));
  Skeleton_Relationship_descriptor_ = Skeleton_descriptor_->nested_type(0);
  Skeleton_Relationship::default_instance_ = new Skeleton_Relationship();
  static const int Skeleton_Relationship_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Relationship, parent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Relationship, child_),
  };
  Skeleton_Relationship_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Skeleton_Relationship_descriptor_,
      Skeleton_Relationship::default_instance_,
      Skeleton_Relationship_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Relationship, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Relationship, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Skeleton_Relationship));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Skeleton_Relationship_descriptor_, Skeleton_Relationship::default_instance_);
  Skeleton_Bone_descriptor_ = Skeleton_descriptor_->nested_type(1);
  Skeleton_Bone::default_instance_ = new Skeleton_Bone();
  static const int Skeleton_Bone_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Bone, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Bone, transform_),
  };
  Skeleton_Bone_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Skeleton_Bone_descriptor_,
      Skeleton_Bone::default_instance_,
      Skeleton_Bone_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Bone, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Skeleton_Bone, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Skeleton_Bone));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Skeleton_Bone_descriptor_, Skeleton_Bone::default_instance_);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Skeleton_descriptor_, Skeleton::default_instance_);
  Mesh::default_instance_->InitAsDefaultInstance();
  Mesh_Layer::default_instance_->InitAsDefaultInstance();
  Quaternion::default_instance_->InitAsDefaultInstance();
  Vector::default_instance_->InitAsDefaultInstance();
  Transform::default_instance_->InitAsDefaultInstance();
  Animation::default_instance_->InitAsDefaultInstance();
  Animation_Keyframe::default_instance_->InitAsDefaultInstance();
  Skeleton::default_instance_->InitAsDefaultInstance();
  Skeleton_Relationship::default_instance_->InitAsDefaultInstance();
  Skeleton_Bone::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_mesh_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\nmesh.proto\022\004mesh\"\225\001\n\004Mesh\022 \n\006layers\030\001 "
    "\003(\0132\020.mesh.Mesh.Layer\022\017\n\007indices\030\002 \003(\r\022\026"
    "\n\016primitive_type\030\003 \002(\005\032B\n\005Layer\022\014\n\004name\030"
    "\001 \002(\t\022\017\n\007columns\030\002 \002(\005\022\014\n\004rows\030\003 \002(\005\022\014\n\004"
    "data\030\004 \003(\002\"8\n\nQuaternion\022\t\n\001r\030\001 \002(\002\022\t\n\001i"
    "\030\002 \002(\002\022\t\n\001j\030\003 \002(\002\022\t\n\001k\030\004 \002(\002\")\n\006Vector\022\t"
    "\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\022\t\n\001z\030\003 \002(\002\"R\n\tTrans"
    "form\022!\n\013translation\030\001 \002(\0132\014.mesh.Vector\022"
    "\"\n\010rotation\030\002 \002(\0132\020.mesh.Quaternion\"\234\001\n\t"
    "Animation\022\014\n\004name\030\001 \002(\t\022\020\n\010duration\030\002 \002("
    "\002\022+\n\tkeyframes\030\003 \003(\0132\030.mesh.Animation.Ke"
    "yframe\032B\n\010Keyframe\022\014\n\004time\030\001 \002(\002\022(\n\017bone"
    "_transforms\030\002 \003(\0132\017.mesh.Transform\"\354\001\n\010S"
    "keleton\022\"\n\005bones\030\001 \003(\0132\023.mesh.Skeleton.B"
    "one\022.\n\thierarchy\030\002 \003(\0132\033.mesh.Skeleton.R"
    "elationship\022#\n\nanimations\030\003 \003(\0132\017.mesh.A"
    "nimation\032-\n\014Relationship\022\016\n\006parent\030\001 \002(\005"
    "\022\r\n\005child\030\002 \002(\005\0328\n\004Bone\022\014\n\004name\030\001 \002(\t\022\"\n"
    "\ttransform\030\002 \002(\0132\017.mesh.Transform", 753,
  &protobuf_BuildDesc_mesh_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mesh_2eproto {
  StaticDescriptorInitializer_mesh_2eproto() {
    protobuf_BuildDesc_mesh_2eproto();
  }
} static_descriptor_initializer_mesh_2eproto_;


// ===================================================================

const ::std::string Mesh_Layer::_default_name_;



Mesh_Layer::Mesh_Layer()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    columns_(0),
    rows_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Mesh_Layer::InitAsDefaultInstance() {}

Mesh_Layer::Mesh_Layer(const Mesh_Layer& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    columns_(0),
    rows_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Mesh_Layer::~Mesh_Layer() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Mesh_Layer::descriptor() {
  if (Mesh_Layer_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Mesh_Layer_descriptor_;
}

const Mesh_Layer& Mesh_Layer::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Mesh_Layer* Mesh_Layer::default_instance_ = NULL;

Mesh_Layer* Mesh_Layer::New() const {
  return new Mesh_Layer;
}

const ::google::protobuf::Descriptor* Mesh_Layer::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Mesh_Layer::GetReflection() const {
  if (Mesh_Layer_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Mesh_Layer_reflection_;
}

// -------------------------------------------------------------------




Mesh::Mesh()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    primitive_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Mesh::InitAsDefaultInstance() {}

Mesh::Mesh(const Mesh& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    primitive_type_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Mesh::~Mesh() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Mesh::descriptor() {
  if (Mesh_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Mesh_descriptor_;
}

const Mesh& Mesh::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Mesh* Mesh::default_instance_ = NULL;

Mesh* Mesh::New() const {
  return new Mesh;
}

const ::google::protobuf::Descriptor* Mesh::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Mesh::GetReflection() const {
  if (Mesh_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Mesh_reflection_;
}

// ===================================================================





Quaternion::Quaternion()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    r_(0),
    i_(0),
    j_(0),
    k_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Quaternion::InitAsDefaultInstance() {}

Quaternion::Quaternion(const Quaternion& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    r_(0),
    i_(0),
    j_(0),
    k_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Quaternion::~Quaternion() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Quaternion::descriptor() {
  if (Quaternion_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Quaternion_descriptor_;
}

const Quaternion& Quaternion::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Quaternion* Quaternion::default_instance_ = NULL;

Quaternion* Quaternion::New() const {
  return new Quaternion;
}

const ::google::protobuf::Descriptor* Quaternion::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Quaternion::GetReflection() const {
  if (Quaternion_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Quaternion_reflection_;
}

// ===================================================================




Vector::Vector()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0),
    y_(0),
    z_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Vector::InitAsDefaultInstance() {}

Vector::Vector(const Vector& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0),
    y_(0),
    z_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Vector::~Vector() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Vector::descriptor() {
  if (Vector_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Vector_descriptor_;
}

const Vector& Vector::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Vector* Vector::default_instance_ = NULL;

Vector* Vector::New() const {
  return new Vector;
}

const ::google::protobuf::Descriptor* Vector::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Vector::GetReflection() const {
  if (Vector_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Vector_reflection_;
}

// ===================================================================



Transform::Transform()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    translation_(NULL),
    rotation_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Transform::InitAsDefaultInstance() {  translation_ = const_cast< ::mesh::Vector*>(&::mesh::Vector::default_instance());
  rotation_ = const_cast< ::mesh::Quaternion*>(&::mesh::Quaternion::default_instance());
}

Transform::Transform(const Transform& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    translation_(NULL),
    rotation_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Transform::~Transform() {
  if (this != default_instance_) {
    delete translation_;
    delete rotation_;
  }
}

const ::google::protobuf::Descriptor* Transform::descriptor() {
  if (Transform_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Transform_descriptor_;
}

const Transform& Transform::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Transform* Transform::default_instance_ = NULL;

Transform* Transform::New() const {
  return new Transform;
}

const ::google::protobuf::Descriptor* Transform::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Transform::GetReflection() const {
  if (Transform_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Transform_reflection_;
}

// ===================================================================



Animation_Keyframe::Animation_Keyframe()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    time_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Animation_Keyframe::InitAsDefaultInstance() {}

Animation_Keyframe::Animation_Keyframe(const Animation_Keyframe& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    time_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Animation_Keyframe::~Animation_Keyframe() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Animation_Keyframe::descriptor() {
  if (Animation_Keyframe_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Animation_Keyframe_descriptor_;
}

const Animation_Keyframe& Animation_Keyframe::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Animation_Keyframe* Animation_Keyframe::default_instance_ = NULL;

Animation_Keyframe* Animation_Keyframe::New() const {
  return new Animation_Keyframe;
}

const ::google::protobuf::Descriptor* Animation_Keyframe::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Animation_Keyframe::GetReflection() const {
  if (Animation_Keyframe_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Animation_Keyframe_reflection_;
}

// -------------------------------------------------------------------

const ::std::string Animation::_default_name_;


Animation::Animation()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    duration_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Animation::InitAsDefaultInstance() {}

Animation::Animation(const Animation& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    duration_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Animation::~Animation() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Animation::descriptor() {
  if (Animation_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Animation_descriptor_;
}

const Animation& Animation::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Animation* Animation::default_instance_ = NULL;

Animation* Animation::New() const {
  return new Animation;
}

const ::google::protobuf::Descriptor* Animation::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Animation::GetReflection() const {
  if (Animation_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Animation_reflection_;
}

// ===================================================================



Skeleton_Relationship::Skeleton_Relationship()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    parent_(0),
    child_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Skeleton_Relationship::InitAsDefaultInstance() {}

Skeleton_Relationship::Skeleton_Relationship(const Skeleton_Relationship& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    parent_(0),
    child_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Skeleton_Relationship::~Skeleton_Relationship() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Skeleton_Relationship::descriptor() {
  if (Skeleton_Relationship_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Skeleton_Relationship_descriptor_;
}

const Skeleton_Relationship& Skeleton_Relationship::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Skeleton_Relationship* Skeleton_Relationship::default_instance_ = NULL;

Skeleton_Relationship* Skeleton_Relationship::New() const {
  return new Skeleton_Relationship;
}

const ::google::protobuf::Descriptor* Skeleton_Relationship::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Skeleton_Relationship::GetReflection() const {
  if (Skeleton_Relationship_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Skeleton_Relationship_reflection_;
}

// -------------------------------------------------------------------

const ::std::string Skeleton_Bone::_default_name_;

Skeleton_Bone::Skeleton_Bone()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    transform_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Skeleton_Bone::InitAsDefaultInstance() {  transform_ = const_cast< ::mesh::Transform*>(&::mesh::Transform::default_instance());
}

Skeleton_Bone::Skeleton_Bone(const Skeleton_Bone& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    name_(const_cast< ::std::string*>(&_default_name_)),
    transform_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Skeleton_Bone::~Skeleton_Bone() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
    delete transform_;
  }
}

const ::google::protobuf::Descriptor* Skeleton_Bone::descriptor() {
  if (Skeleton_Bone_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Skeleton_Bone_descriptor_;
}

const Skeleton_Bone& Skeleton_Bone::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Skeleton_Bone* Skeleton_Bone::default_instance_ = NULL;

Skeleton_Bone* Skeleton_Bone::New() const {
  return new Skeleton_Bone;
}

const ::google::protobuf::Descriptor* Skeleton_Bone::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Skeleton_Bone::GetReflection() const {
  if (Skeleton_Bone_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Skeleton_Bone_reflection_;
}

// -------------------------------------------------------------------




Skeleton::Skeleton()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Skeleton::InitAsDefaultInstance() {}

Skeleton::Skeleton(const Skeleton& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Skeleton::~Skeleton() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Skeleton::descriptor() {
  if (Skeleton_descriptor_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Skeleton_descriptor_;
}

const Skeleton& Skeleton::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return *default_instance_;
}

Skeleton* Skeleton::default_instance_ = NULL;

Skeleton* Skeleton::New() const {
  return new Skeleton;
}

const ::google::protobuf::Descriptor* Skeleton::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Skeleton::GetReflection() const {
  if (Skeleton_reflection_ == NULL) protobuf_BuildDesc_mesh_2eproto();
  return Skeleton_reflection_;
}

}  // namespace mesh
