#!/bin/sh

cd /usr/share/pink-pony

if [ $# -ge 1 ]; then
    /usr/lib/Pony $1
else
    if [ ! -f ~/.config/pony.options ]; then
	mkdir -p ~/.config/
	cp /etc/pony.options ~/.config/pony.options
    fi
    
    /usr/lib/Pony ~/.config/pony.options
fi